In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import requests,json
%matplotlib inline

In [ ]:
df = pd.read_csv(r"C:\Users\Comp\experiment_01.csv")
df.head()

In [3]:
from sklearn.preprocessing import StandardScaler

In [4]:
scaler = StandardScaler()

In [5]:
scaler.fit(df.drop('Machining_Process',axis=1))

StandardScaler(copy=True, with_mean=True, with_std=True)

In [6]:
scaler.fit(df.drop('Machining_Process',axis=1))

StandardScaler(copy=True, with_mean=True, with_std=True)

In [7]:
scaled_features = scaler.transform(df.drop('Machining_Process',axis=1))
scaled_features

array([[ 5.53436751,  0.08767454, -0.04119   , ...,  0.        ,
        -1.61774222,  3.93501906],
       [ 5.53436751, -1.75122485, -3.43100195, ...,  0.        ,
        -1.51686044,  3.93501906],
       [ 5.29375275, -2.94310409, -0.10172236, ...,  0.        ,
        -1.4411991 ,  3.93501906],
       ...,
       [-1.3231531 ,  0.05787756, -0.88864299, ...,  0.        ,
         1.71135669,  3.93501906],
       [-1.3231531 ,  0.11321481,  0.80626299, ...,  0.        ,
         1.71135669,  3.93501906],
       [-1.3231531 ,  0.11747152,  0.86631108, ...,  0.        ,
         1.71135669,  3.93501906]])

In [8]:
df_feat = pd.DataFrame(scaled_features,columns=df.columns[:-1])
df_feat.head()

X1_ActualPosition  X1_ActualVelocity  X1_ActualAcceleration  \
0           5.534368           0.087675              -0.041190   
1           5.534368          -1.751225              -3.431002   
2           5.293753          -2.943104              -0.101722   
3           5.053138          -2.977158              -0.041190   
4           4.932831          -2.960131              -0.223271   

   X1_CommandPosition  X1_CommandVelocity  X1_CommandAcceleration  \
0            5.538777            0.087939               -0.000925   
1            5.538777           -2.229522               -4.405549   
2            5.297965           -2.962249               -0.000926   
3            5.057154           -2.962249               -0.000926   
4            4.816342           -2.962249               -0.000924   

   X1_CurrentFeedback  X1_DCBusVoltage  X1_OutputCurrent  X1_OutputVoltage  \
0            0.114051        -2.016592          5.418415         -1.257412   
1           -2.131451         3.456409          3.684062          1.975154   
2           -1.663301         1.933372          3.684062          3.124581   
3           -1.160697         1.602277          1.949709          3.077344   
4           -1.077605         1.072525          3.684062          3.108835   

          ...           S1_CommandAcceleration  S1_CurrentFeedback  \
0         ...                        -0.069007           -3.628983   
1         ...                        -0.069007           -3.776432   
2         ...                        -0.069007           -3.628983   
3         ...                        -0.069007           -3.756820   
4         ...                        -0.069007           -3.683096   

   S1_DCBusVoltage  S1_OutputCurrent  S1_OutputVoltage  S1_OutputPower  \
0        -4.171734          3.318274         -5.612544       -4.643695   
1        -4.171734          2.941765         -5.612544       -4.643728   
2        -4.171734          2.941765         -5.612544       -4.643689   
3        -4.171734          2.941765         -5.612544       -4.643685   
4        -4.171734          2.941765         -5.612544       -4.643661   

   S1_SystemInertia  M1_CURRENT_PROGRAM_NUMBER  M1_sequence_number  \
0               0.0                        0.0           -1.617742   
1               0.0                        0.0           -1.516860   
2               0.0                        0.0           -1.441199   
3               0.0                        0.0           -1.441199   
4               0.0                        0.0           -1.441199   

   M1_CURRENT_FEEDRATE  
0             3.935019  
1             3.935019  
2             3.935019  
3             3.935019  
4             3.935019  

[5 rows x 47 columns]

In [72]:
from sklearn.model_selection import train_test_split

In [73]:
X_train, X_test, y_train, y_test = train_test_split(scaled_features,df['Machining_Process'],
                                                    test_size=0.30)

In [74]:
from sklearn.svm import SVC

In [75]:
C = 10
model = SVC(kernel='rbf', gamma=0.1, C=C)

In [76]:
model.fit(X_train,y_train)

SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.1, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [77]:
pred = model.predict(X_test)

In [78]:
from sklearn.metrics import classification_report,confusion_matrix

In [79]:
print(confusion_matrix(y_test,pred))

[[129  11]
 [  2 175]]


In [1]:
(304 / 317)*100

95.89905362776025

In [18]:
df_feat.columns

Index(['X1_ActualPosition', 'X1_ActualVelocity', 'X1_ActualAcceleration',
       'X1_CommandPosition', 'X1_CommandVelocity', 'X1_CommandAcceleration',
       'X1_CurrentFeedback', 'X1_DCBusVoltage', 'X1_OutputCurrent',
       'X1_OutputVoltage', 'X1_OutputPower', 'Y1_ActualPosition',
       'Y1_ActualVelocity', 'Y1_ActualAcceleration', 'Y1_CommandPosition',
       'Y1_CommandVelocity', 'Y1_CommandAcceleration', 'Y1_CurrentFeedback',
       'Y1_DCBusVoltage', 'Y1_OutputCurrent', 'Y1_OutputVoltage',
       'Y1_OutputPower', 'Z1_ActualPosition', 'Z1_ActualVelocity',
       'Z1_ActualAcceleration', 'Z1_CommandPosition', 'Z1_CommandVelocity',
       'Z1_CommandAcceleration', 'Z1_CurrentFeedback', 'Z1_DCBusVoltage',
       'Z1_OutputCurrent', 'Z1_OutputVoltage', 'S1_ActualPosition',
       'S1_ActualVelocity', 'S1_ActualAcceleration', 'S1_CommandPosition',
       'S1_CommandVelocity', 'S1_CommandAcceleration', 'S1_CurrentFeedback',
       'S1_DCBusVoltage', 'S1_OutputCurrent', 'S1_OutputVolt

In [19]:
from sklearn.externals import joblib

In [20]:
model

SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.1, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [21]:
joblib.dump(model,'svm_jl')

['svm_jl']

In [22]:
abc = joblib.load('svm_jl')

In [23]:
new_test = np.array([[1.44E+02, "1.50E-01", 7.50E+01, 1.44E+02, 0.00E+00, 0.00E+00, -3.80E+00, 5.28E-02, 3.26E+02, 2.94E+00, 2.16E-05, 9.84E+01, -6.22E+00, 1.25E+01, 9.83E+01, -6.00E+00, 0.00E+00, -5.21E+00, 8.90E-02, 3.24E+02, 1.25E+01, 1.08E-03, 2.95E+01, 0.00E+00, 0.00E+00, 2.95E+01, 0.00E+00, 0.00E+00, 0.00E+00, 0.00E+00, 0.00E+00, 0.00E+00, 7.50E+02, 5.33E+01, -2.54E+01, 7.51E+02, 5.33E+01, -9.54E-07, 1.95E+01, 1.01E+00, 3.18E+02, 1.17E+02, 1.95E-01, 1.20E+01, 1.00E+00, 3.70E+01, 6.00E+00]])
abc.predict(new_test)

array([1], dtype=int64)

In [280]:
file = open(r'C:\Users\Comp\jsondemo.txt', 'r', encoding='utf-8')
trial = json.load(file)
file.close()
trial

{'X1_ActualPosition': '198.0',
 'X1_ActualVelocity': '-10.8',
 'X1_ActualAcceleration': '-350.00',
 'X1_CommandPosition': '198.00',
 'X1_CommandVelocity': '-13.6',
 'X1_CommandAcceleration': '-358.000000',
 'X1_CurrentFeedback': '-10.90',
 'X1_DCBusVoltage': '0.1860',
 'X1_OutputCurrent': '328.0',
 'X1_OutputVoltage': '23.30',
 'X1_OutputPower': '0.00448',
 'Y1_ActualPosition': '158.00',
 'Y1_ActualVelocity': '-19.80',
 'Y1_ActualAcceleration': '-750.00',
 'Y1_CommandPosition': '157.00',
 'Y1_CommandVelocity': '-24.60',
 'Y1_CommandAcceleration': '-647.00',
 'Y1_CurrentFeedback': '-14.50',
 'Y1_DCBusVoltage': '0.281',
 'Y1_OutputCurrent': '325.00',
 'Y1_OutputVoltage': '37.80',
 'Y1_OutputPower': '0.0126',
 'Z1_ActualPosition': '119.00',
 'Z1_ActualVelocity': '-20.30',
 'Z1_ActualAcceleration': '-712.00',
 'Z1_CommandPosition': '118.00',
 'Z1_CommandVelocity': '-25.60',
 'Z1_CommandAcceleration': '-674.00',
 'Z1_CurrentFeedback': '0',
 'Z1_DCBusVoltage': '0',
 'Z1_OutputCurrent': '0',


In [92]:

url = 'http://127.0.0.1:9000/pred'




In [99]:
data = json.dumps({"X1_ActualPosition":"198.0", "X1_ActualVelocity":"-10.8", "X1_ActualAcceleration":"-350.00", "X1_CommandPosition":"198.00", "X1_CommandVelocity":"-13.6", "X1_CommandAcceleration":"-358.000000", "X1_CurrentFeedback":"-10.90", "X1_DCBusVoltage":"0.1860", "X1_OutputCurrent":"328.0", "X1_OutputVoltage":"23.30", "X1_OutputPower":"0.00448", "Y1_ActualPosition":"158.00", "Y1_ActualVelocity":"-19.80", "Y1_ActualAcceleration":"-750.00", "Y1_CommandPosition":"157.00", "Y1_CommandVelocity":"-24.60", "Y1_CommandAcceleration":"-647.00", "Y1_CurrentFeedback":"-14.50", "Y1_DCBusVoltage":"0.281", "Y1_OutputCurrent":"325.00", "Y1_OutputVoltage":"37.80", "Y1_OutputPower":"0.0126", "Z1_ActualPosition":"119.00", "Z1_ActualVelocity":"-20.30", "Z1_ActualAcceleration":"-712.00", "Z1_CommandPosition":"118.00", "Z1_CommandVelocity":"-25.60", "Z1_CommandAcceleration":"-674.00", "Z1_CurrentFeedback":"0", "Z1_DCBusVoltage":"0", "Z1_OutputCurrent":"0", "Z1_OutputVoltage":"0", "S1_ActualPosition":"-361.00", "S1_ActualVelocity":"0", "S1_ActualAcceleration":"0.25", "S1_CommandPosition":"-361.00", "S1_CommandVelocity":"0", "S1_CommandAcceleration":"0", "S1_CurrentFeedback":"-0.288", "S1_DCBusVoltage":"2.740000e-19", "S1_OutputCurrent":"328.00", "S1_OutputVoltage":"0", "S1_OutputPower":"6.960000e-07", "S1_SystemInertia":"12.00", "M1_CURRENT_PROGRAM_NUMBER":"1", "M1_sequence_number":"4", "M1_CURRENT_FEEDRATE":"5"})

In [100]:
r = requests.post(url, data)

In [97]:
xas = np.array(r.json())

JSONDecodeError: Expecting value: line 1 column 1 (char 0)